# Generated by Django 3.2 on 2023-05-14 19:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='description',
            field=models.TextField(help_text="what's interesting about this hotel?", null=True, validators=[django.core.validators.MinLengthValidator(50), django.core.validators.MaxLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/%H-%S-%M/'),
        ),
    ]
